### ISSUE TITLE
Windows Pro VS Professional

### ISSUE THREAD

**Issue by hoquem1** [strezag/sitecore-containers-prerequisites#4]
My PC from Lenovo came with Windows 10 Pro. Scanner can't seem to realize that it is short for Professional. 
Minor improvement suggesion.
See the screenshot. 
![Docker-scanner](https://user-images.githubusercontent.com/4118915/110010479-f680f900-7ce3-11eb-9ddd-668e245fba29.png)

**Comment by strezag** [comment]
Thank you for flagging this @hoquem1. 
I've added [a fix](https://github.com/strezag/sitecore-containers-prerequisites/commit/9cb4596740c8d4da8c7123bcfd8045a2dfa95bd9) for this.  

If you don't mind confirming before I close this out, that would be great!

**Comment by hoquem1** [comment]
The fix worked.
